### ISSUE TITLE
Strange position_dodge error in ggplot?

### ISSUE THREAD

**Issue by pajodu** [minisciencegirl/studyGroup#127]
Hi all! This is my first issue (at least here), so let me know if there are any issues with my issue.

I don't understand this behavior in ggplot, where geom_errorbar width can take a vector, but position_dodge acts up when that vector isn't all identical numbers. Example 2 is the functionality I was looking for.

``` r
# ggplot position_dodge error?
# Having a vector for width of error bars is fine,
# but only if all values equal!
library(ggplot2)

EBW <- function(ebw, lbw=ebw) {
  # data frame of values with two groupings
  df <- data.frame(val=1:6, g1=c(1:3,1:3), g2=rep(c("a","b"),3),
                   se=(1:6)/10, # length of error bars
                   bw=ebw) # error bar widths
  df[6, "bw"] <- lbw # change last error bar width

  # graph with error bars
  print(ggplot(data=df, aes(x=g1, y=val, fill=g2)) +
  geom_bar(stat="identity", position=position_dodge(), colour="black") +
    ggtitle(sprintf("Last error bar width: %.1f", lbw)) +
    geom_errorbar(aes(ymin=val-se, ymax=val+se),
                  width=df$bw, # vector works here, but not with different values
                  position=position_dodge(.9)))
}

dw <- .2
EBW(dw, .2)  # 1 fine, same as other widths
EBW(dw, .1)  # 2 alignment off, with warning
EBW(dw, NA)  # 3 alignment off, but no warning
EBW(dw, NaN) # 4 alignment off, but no warning
EBW(dw, Inf) # 5 crash with unhelpful error message
```

**Comment by katieannemills** [comment]
About as pretty as cutting a birthday cake with a chainsaw, but here we are:

```
library(ggplot2)

EBW <- function(ebw, lbw=ebw) {
  #... exactly your function except with plot = ggplot... instead of print(ggplot... ...

  hackaroo = ggplot_build(plot)$data[[1]]
  hackaroo = hackaroo[with(hackaroo, order(ymax)), ]
  x_force = hackaroo$x

 # your same plot but with the geom_errorbar aes x position explicitly set
  plot = ggplot(data=df, aes(x=g1, y=val, fill=g2)) +
    geom_bar(stat="identity", position=position_dodge(), colour="black") +
    ggtitle(sprintf("Last error bar width: %.1f", lbw)) +
    geom_errorbar(aes(x=x_force, ymin=val-se, ymax=val+se),
                  width=df$bw, # vector works here, but not with different values
                  position=position_dodge(.9))

  print(plot)
}
```

The trick being to set the x positions in `geom_errorbar`'s `aes` explicitly, since something about that is going off the rails otherwise. In the solution above I prepare the plot as usual so I can post-facto see where `dodge` put everything, get those x positions, resort them since they appear in ggplot's guts in a different order than they (apparently) need to be specified in `aes`, and redo the whole thing with the forced x positions. The point being, that the only thing wrong is in how the x positions of the error bars are being calculated.

Also worth noting and going back to the original code, this doesn't happen when the bars aren't grouped (ie when `position_dodge` doesn't actually have to do anything; it also doesn't happen if you set _both_ error bar widths in a group to a custom value - ie add `df[3, "bw"] <- lbw` to your function).

My finger would be hovering over the big red bug report button right about now; I struggle to imagine why the (relative) widths of an annotation should be tangled up with the position of an entirely different (if related) element - the tight coupling there kind of surprises me~

**Comment by pajodu** [comment]
Thank you Bill! 

That hack fixes things for that test case, but not for a more complicated case I attach. I'm trying to build a generic routine to compare group levels where there may be missing, empty or single cases 

Since this does look like there may be something buggy in ggplot, how would I submit that? 

Also, am I responding to this in the best way, i.e. via email, or should it be via GitHub? 

Thanks! 

Patrick Dubois , BSc, MA 
PhD Student, UBC Psychology 
Kenny 3522

**Comment by katieannemills** [comment]
Bug reports for ggplot2 go here: https://github.com/hadley/ggplot2/issues

Do have a look through the existing issues first though, to make sure it's not a duplicate; otherwise, the MWE you showed in your top post is an A+ bug report IMO; I might leave off the cases with the `NA`s etc, and just focus on the case that ought to be giving sensible results (your second one).

Re: email vs github, you should reply in whatever method you find most convenient (though the whole thread history gets reposted with email replies). Personally, I always click through to github and read things there to see if folks have edited their post, which doesn't get reflected in email.
