### ISSUE TITLE
Learn how to use DiagrammeR for your graphing needs!

### ISSUE THREAD

**Issue by minisciencegirl** [minisciencegirl/studyGroup#48]
What better way to learn how to use DiagrammeR (https://github.com/rich-iannone/DiagrammeR) for visualizing your data than from the creator of this package, @rich-iannone!! 
Time: 9/30, 4pm
Location: Biodiversity Room 224

**Comment by jennybc** [comment]
So looking forward to this.

**Comment by rich-iannone** [comment]
Me too! Really excited to be presenting!

**Comment by minisciencegirl** [comment]
@rozdakin: Is it possible to get BioDiv 224 for September 30, 4 - 5:30 pm? Thank you so much!

**Comment by rozdakin** [comment]
Yes, we've got it. I did this earlier and updated the original post when I did...

**Comment by minisciencegirl** [comment]
Doh I completely missed that. You are awesome! Thanks a bunch Roz. :-)

**Comment by rich-iannone** [comment]
Quick update leading up to the day of talk: I've prepared an exercise file (R script) for the code-along portion and it's at https://gist.github.com/rich-iannone/f28fbf8f70475f1639c1. This information is also contained in the talk (with shortened link http://bit.ly/1WpFKnz) so that people can do some `install.packages` and `install_github` before the code-along begins.

I'll post the actual presentation here in a day or two.

**Comment by rich-iannone** [comment]
Okay, so I can't attach a Keynote file here (nor a zipped Keynote). I guess we'll see the presentation a bit later. See you all soon.

**Comment by minisciencegirl** [comment]
@rich-iannone: Would it be possible to get a PDF of your gorgeous presentation? It would be cool to have this included in the #R Utility Belt (see Issue #29).
Thanks for a fantastic presentation!!

**Comment by rich-iannone** [comment]
@minisciencegirl thanks again for the invite! It was a lot of fun. Could I send the PDF by email? It's weird but the uploader here won't accept the PDF of the presentation. (Just email me at riannone@me.com and I'll respond back with the attached PDF). Also, feel free to distribute it in any manner when you receive it.
