### ISSUE TITLE
Introduction to Cloud Computing / March 14

### ISSUE THREAD

**Issue by katieannemills** [minisciencegirl/studyGroup#90]
**What**: Walk through the basics of using Amazon Web Services to do powerful data analysis in the cloud.
**When**: Monday, March 14, 1 PM
**Where**: [UBC Main Campus, Biodiversity Bldg Rm 224](https://www.google.ca/maps/place/Beaty+Biodiversity+Museum,+Vancouver,+BC+V6T+1Z4/@49.2634989,-123.2524072,17z/data=!3m1!4b1!4m2!3m1!1s0x548672c9f84be123:0x1c431143106eb830)
**Who**: absolutely everyone! Beginners especially welcome!

Cloud computing gives researchers the opportunity to use very powerful computing resources for less than the cost of a cup of coffee, without the hassle of setting up and maintaining lots of complicated computers in house; the cloud also provides an opportunity to share data even at large scale. @mstrimas and @BillMills will be introducing the basics of computing in the cloud - how to get set up on EC2 and host and use data from S3.

**Comment by jstaf** [comment]
I think it's worth advertising the free cloud computing resources offered by Compute Canada. It doesn't really make sense to use Amazon's stuff for research when Compute Canada provides [significantly better resources](https://www.westgrid.ca/support/systems/) for absolutely free. 

Any academic researcher can get an account here: https://www.computecanada.ca/research-portal/account-management/apply-for-an-account/

**Comment by radaniba** [comment]
Cool but there is no docs about what it is offered to researchers, what kind of machines and compute power they have ?

Amazon is not that expensive ! It depends on how big are the projects indeed but there is always more than one option

**Comment by jstaf** [comment]
Depends on the system, but you can pretty much get any amount of computing power you need. The most I've used at one time was 32 cores, but I've heard of someone using 6400 processor threads before at HPCVL. Compute Canada's stuff has a number of other advantages over Amazon besides just being free: you don't need to bother setting up/micromanaging your instances, a lot of software you'd need is already there, file backup is free and automated, your data is secure, and signup is waaaaayyy easier (just get your account approved, then login to the system you want). 

[Hermes/Nestor](https://www.westgrid.ca/support/quickstart/hermes_nestor) and [Bugaboo](https://www.westgrid.ca/support/quickstart/Bugaboo) are probably the two systems best suited for bioinformatics work if you're working through WestGrid  (did all my NGS stuff on Hermes/Nestor as a grad student), not sure about other fields.

Anyhow, I'll stop pushing it so hard, but the Compute Canada stuff is definitely worth looking into.

**Comment by radaniba** [comment]
I think indeed it is interesting. Will look into it carefully, thanks for sharing the info

**Comment by jstaf** [comment]
No problem- honestly I'm just trying to spread the word around! Compute Canada and its member organizations need to advertise themselves much better to the user base they've been funded to support (i.e. academic researchers).

**Comment by katieannemills** [comment]
Thanks, @kazi11! I am free's number one fan - is there a hello world tutorial I can do somewhere to get started? I will totally present compute canada at this session if I can get it working by then.

**Comment by radaniba** [comment]
@BillMills I am pretty sure it is like you submit for an account, once approved you will be able to log in to the servers via SSH or any other protocol to do a routine stuff we do on remote servers. 

@kazi11 what is a Compute Canada Role Identifier (CCRI) ? I am actually not able to register because of this, no readme, no docs about it.

**Comment by jstaf** [comment]
@BillMills, @radaniba - Here's my attempt at a "Hello world" tutorial for WestGrid. The process for other Compute Canada members are quite similar.

To get an account (usually takes ~3 days, most of which is waiting for the inital PI account):
- Get your PI to register for an account @ [ccdb.computecanada.ca](ccdb.computecanada.ca) (or just register yourself if you are a PI/faculty).
- Wait for the PI account to get approved. When this happens, they receive a CCRI id via email (they can also login to ccdb.computecanada.ca to see the CCRI).
- Sign up under your PI's account- you'll need their CCRI. Your PI gets an email asking them to "approve" you.
- Sign up for a consortium account @ [ccdb.computecanada.ca/](ccdb.computecanada.ca) ("My Account" -> "Apply for Consortium Account"). You guys should sign up under WestGrid, since that's the western Canada group.

To login to a system (example for Hermes): `ssh -X userName@hermes.westgrid.ca`. The `-X` enables you to see any pop-up windows/graphics you create.

To transfer files: `sftp userName@hermes.westgrid.ca`

Example PBS job script for WestGrid (`.pbs`), it's basically just a shell script with a few `#PBS` things at the top to request the resources you need:

``` bash
#!/bin/bash

# amount of time requested in hh:mm:ss
#PBS -l walltime=1:00:00 
# number of processors requested
#PBS -l procs=1 
# memory requested
#PBS -l mem=1gb 

echo 'Hello world!'
pwd # pretty sure jobs start in your home directory

# you load software to your $PATH like this
module load python
python --version # just showing that you can use python now
```

To submit a job: `qsub yourScript.pbs`
To check status of jobs: `qstat -u yourUserName`
To delete a job (get JOB_ID from `qstat`): `qdel JOB_ID`

Upon job completion, `stdout` (JOB_ID.o) and `stderr` (JOB_ID.e) logs appear in your home directory. The files from your run appear in your directories as they get created/processed by the job.

**Comment by radaniba** [comment]
Thanks for sharing @kazi11 will let some people know about it

**Comment by morien** [comment]
Worth noting here: if your use is 'heavy'as defined by Compute Canada then
you must submit a use application. There's more info on their website. I'm
on my phone or I'd provide links myself.

**Comment by katieannemills** [comment]
That's awesome, thanks @kazi11! We'll be sure to mention it during our session; it's a bit tough for me personally, since all my cloud computing needs are actually hobby projects unrelated to anything my PI would sign off on, but we'll make sure people know more broadly nonetheless.

**Comment by mstrimas** [comment]
For those attending the cloud computing session on Monday, if you're able to [sign up for an Amazon Web Services account](https://portal.aws.amazon.com/gp/aws/developer/registration/index.html) before the session, that will speed things up. Note that they ask for a credit card number, but you won't be charged for anything unbeknownst to you.

Also, if you're feeling especially ambitious, you can install the AWS command line interface:
- [Mac & Linux](http://docs.aws.amazon.com/cli/latest/userguide/installing.html#install-bundle-other-os)
- [Windows](http://docs.aws.amazon.com/cli/latest/userguide/installing.html#install-msi-on-windows)

Thanks!

**Comment by mstrimas** [comment]
The notes I'll be referring to tomorrow are now online: [Part I](http://strimas.com/r/rstudio-cloud-1/) and [Part II](http://strimas.com/r/rstudio-cloud-2/)

**Comment by SimonGoring** [comment]
These notes look fantastic. Thanks!  Just out of curiosity, is this a Jekyll site?  I'm just trying to set one up myself.

**Comment by mstrimas** [comment]
@SimonGoring Yep, [source code](https://github.com/mstrimas/mstrimas.github.io) is on GitHub. Jekyll isn't quite as intuitive to use as I'd hoped, but now that I've got a good workflow set up for the site I'm quite happy with it. Let me know if you have any questions, I'd be happy to help.

**Comment by jooolia** [comment]
I found this which was helpful for getting around the error we were getting while trying to get the data from S3: https://forums.aws.amazon.com/thread.jspa?threadID=173124

**Comment by mstrimas** [comment]
Thanks @jooolia, and apologies to everyone for that last bit not working.
