### ISSUE TITLE
R (m)Apps with Shiny & Leaflet / March 7

### ISSUE THREAD

**Issue by katieannemills** [minisciencegirl/studyGroup#98]
**What**: an introduction to to making apps and maps with shiny and leaflet
**When**: Monday, March 7, 1 PM
**Where**: [UBC Main Campus, Biodiversity Bldg Rm 224](https://www.google.ca/maps/place/Beaty+Biodiversity+Museum,+Vancouver,+BC+V6T+1Z4/@49.2634989,-123.2524072,17z/data=!3m1!4b1!4m2!3m1!1s0x548672c9f84be123:0x1c431143106eb830)
**Who**: absolutely everyone! Beginners especially welcome!

@simongoring will be introducing shiny and leaflet - details forthcoming!

**Comment by SimonGoring** [comment]
Hi all, there's a first draft of the Tutorial up here:
https://github.com/SimonGoring/ShinyLeaflet-tutorial

Still a bit rough, but it should give an idea of what I hope to cover.  Note that there's one data file you need to use, and, because we use Shiny & Leaflet you'll need an internet connection & RStudio (or some way to run the Shiny app).

Looking forward to Monday!

**Comment by katieannemills** [comment]
Hooray maps & web stuff, I can't wait! :D
